AllCops:
  Exclude:
    - '**/*.gemspec'
    - 'bin/*'
    - 'vendor/bundle/**/*'
    - 'tmp/**/*'
LineLength:
  Max: 160
MethodLength:
  Max: 30
ClassLength:
  Max: 160
CyclomaticComplexity:
  Max: 10
PerceivedComplexity:
  Max: 10
AbcSize:
  Max: 40
Documentation:
  Enabled: false
