AllCops:
  Exclude:
    - '**/*.gemspec'
    - 'bin/*'
    - 'vendor/bundle/**/*'
    - 'tmp/**/*'
LineLength:
  Enabled: false
MethodLength:
  Max: 30
CyclomaticComplexity:
  Max: 10
PerceivedComplexity:
  Max: 10
Documentation:
  Enabled: false
Style/RegexpLiteral:
  MaxSlashes: 0
AbcSize:
  Enabled: false
