# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'active_support'
require 'rubygems'
require 'pry'
Bundler.require(:development, :test)

ActiveSupport::Dependencies.autoload_paths << File.expand_path('../lib', File.dirname(__FILE__))

RSpec.configure do |config|
  config.filter_run focus: true
  config.run_all_when_everything_filtered = true
  config.order = 'random'
end
